version: '3.5'

services:
  app:
    build: .
    image: local/hmonit:latest
    environment:
      APP_SYSTEM_CODE: hmonit
      SERVICES_CONFIG_FILE: services.json
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
